services:
  app:
    build:
      context: .
      target: developer
    restart: no
    container_name: app
    hostname: app
    ports:
      - 80:80
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - .:/var/www/html/
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: mariadb:11.5.2-noble
    container_name: mariadb
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7.4.0
    container_name: redis
    restart: no

volumes:
  db_data: